#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

# availabilty of python
py=$(which py || which python || which python3)
if [[ -z $py ]]
then 
  echo "No python found"
  exit 0
fi

# go to the root of the git repo
cd $(git rev-parse --show-toplevel)

# path to sompy python scripts
sompy=$(pwd)/submodules/sompy/somutil

# files regarded as text files to be cleaned
txts=
# extensions of text files sorted by likeliness
xtxt="h cpp cmd py md lua sh"

for file in $(git diff-index --cached --name-only HEAD); do
  if [[ -f $file ]]
  then
    for ext in $xtxt; do
      if [[ $file == *.$ext ]]; then txts="$txts $file"; break; fi
    done
  fi
done

if [[ -n $txts ]]; then
  echo cleaning text files
  $py $sompy/cleanTxt.py -l $txts
fi
for file in $txts; do git add $file; done
